### ISSUE TITLE
It seems to be broken on OSX

### ISSUE THREAD

**Issue by mindreframer** [dreadl0ck/zeus#1]
![screen shot 2017-02-14 at 12 44 22](https://cloud.githubusercontent.com/assets/1232/22927761/5b79f3bc-f2b3-11e6-9760-08659bc31e36.png)

**Comment by dreadl0ck** [comment]
Hey sorry for that - you have to change the color theme.
The dark mode has black text colors, which are not visible on a black background.
Change to the default theme. -> colors default
Or change your terminal background color.
I really like the dark solarized color themes.
cheers

**Comment by dreadl0ck** [comment]
I've changed the zeus project theme to default in the config and updated the readme to avoid further confusion. Simply pull and it should be fine.

**Comment by mindreframer** [comment]
Hey, you are right! 

changing colors to default seems to work on dark themes... 

![screen shot 2017-02-14 at 13 04 26](https://cloud.githubusercontent.com/assets/1232/22928329/25bc319c-f2b6-11e6-837f-0bd090ceffca.png)

Looks like a nice idea, look forward to use it when it is more stable!

**Comment by kataras** [comment]
I don't know about you but I think this package is going to be the next build tool for gophers.

I'm seriously considering the use of ZEUS ('Δίας' or 'Ζεύς' in Greek ) on my Iris daily jobs :) 

Good job @dreadl0ck , don't relax, code-code!!

**Comment by dreadl0ck** [comment]
Great to hear, many thanks @kataras 

Got 2 weeks of exams left, after that I'll finish that thing as fast as possible! :)
