### ISSUE TITLE
shell script chains doesn't work anymore?

### ISSUE THREAD

**Issue by franciscocpg** [dreadl0ck/zeus#10]
I've updated zeus and moved my *.sh files from `zeus` to `zeus/scripts` but `@zeus-chain` inside those *.sh files aren't working anymore (they are not called).

Is that a problem or things have changed? (It's not clear for me in the docs).

**Comment by dreadl0ck** [comment]
Yes there were some changes, the Docs have been updated.
Header tags have been removed completely, all script data is now supplied in the zeus/commands.yml yaml file. You can now use multiple scripting languages, generate standalone versions of the scripts etc.

**Comment by franciscocpg** [comment]
But I have a huge project with a lot of scripts and chains. Should I migrate all of them?

**Comment by dreadl0ck** [comment]
I highly recommend to do so. Especially for large projects I think you will like the new codebase. Check out the 'edit' command!
