### ISSUE TITLE
Using a dependency tool

### ISSUE THREAD

**Issue by franciscocpg** [dreadl0ck/zeus#5]
How about using a dependency tool like [dep](https://github.com/golang/dep/) or [glide](https://github.com/Masterminds/glide)?

**Comment by dreadl0ck** [comment]
Hi there, the project is currently vendored with godep.
If you think there's a better alternative, let me know why you think so!
cheers

**Comment by franciscocpg** [comment]
My fault @dreadl0ck 
I didn't notice the project is already using `godep`.
Forget about this issue, :grimacing:
