### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by boljen** [dreadl0ck/zeus#6]
Hi,

Thanks for your effort on the tool, however, it would be a shame if people didn't make us of your work because they can't find it. More specifically, when people can't find it on Google.

Of course "zeus" didn't return any results on the first couple of pages, but  "zeus build" didn't return any either, nor "zeus download" or "zeus go". I ended up scrolling through my Github stars instead to find this project. It turns out that "zeus golang" does return this project as first hit, but that's equivalent to looking for gnu make using "make clang".

As far as I know, the age of a page has a positive effect on search engine ranking. Perhaps you could build a simple github page website with a bit of documentation and some downloadable binaries? This could potentially make it a lot easier for people to find your tool with keywords like "zeus build" and "zeus download".

My 2 cents

**Comment by dreadl0ck** [comment]
Hi there,

thanks for your suggestions, you are absolutely right!

I did some research on the topic and performed the following steps:

- added github page: https://dreadl0ck.github.io/zeus/
- enabled jekyll SEO Plugin for the pages theme + added meta tag with custom keywords
- provided downloadable binaries & a first gtihub release
- added meta tag comment to the README.md as proposed here: https://github.com/aloisdg/awesome-regex/issues/9
- added multiple github wiki pages
- updated project topics for github search

let's see if that helps :)

cheers
